### ISSUE TITLE
got "fatal: Not a git repository (or any of the parent directories): .git" when compiling libinvm-cim

### ISSUE THREAD

**Issue by yide1728** [01org/libinvm-cim#2]
#wget https://github.com/01org/libinvm-cim/archive/v1.0.0.1043.tar.gz
#tar xvf libinvm-cim-1.0.0.1041.tar.gz
#cd libinvm-cim-1.0.0.1041 
#make

**Comment by nkothapa** [comment]
Fixed it in the latest release, Thanks for the report!
